var files =
[
    [ "alloc.tmp.h", "alloc_8tmp_8h.html", "alloc_8tmp_8h" ],
    [ "cerror.cpp", "cerror_8cpp.html", "cerror_8cpp" ],
    [ "cerror.h", "cerror_8h.html", "cerror_8h" ],
    [ "checkedexception.cpp", "checkedexception_8cpp.html", null ],
    [ "checkedexception.h", "checkedexception_8h.html", null ],
    [ "csv.h", "csv_8h.html", "csv_8h" ],
    [ "filealloc.cpp", "filealloc_8cpp.html", "filealloc_8cpp" ],
    [ "fileerror.cpp", "fileerror_8cpp.html", "fileerror_8cpp" ],
    [ "fileio.cpp", "fileio_8cpp.html", null ],
    [ "fileio.h", "fileio_8h.html", null ],
    [ "kpfutils.h", "kpfutils_8h.html", "kpfutils_8h" ],
    [ "lcexcept.cpp", "lcexcept_8cpp.html", null ],
    [ "lcexcept.h", "lcexcept_8h.html", null ],
    [ "lcin.cpp", "lcin_8cpp.html", "lcin_8cpp" ],
    [ "lcio.h", "lcio_8h.html", "lcio_8h" ],
    [ "lcmanip.cpp", "lcmanip_8cpp.html", "lcmanip_8cpp" ],
    [ "lcout.cpp", "lcout_8cpp.html", "lcout_8cpp" ],
    [ "nan.cpp", "nan_8cpp.html", "nan_8cpp" ],
    [ "nan.h", "nan_8h.html", "nan_8h" ],
    [ "readnames.cpp", "readnames_8cpp.html", "readnames_8cpp" ],
    [ "readtable.cpp", "readtable_8cpp.html", "readtable_8cpp" ],
    [ "stats.tmp.h", "stats_8tmp_8h.html", "stats_8tmp_8h" ],
    [ "stats_except.cpp", "stats__except_8cpp.html", null ],
    [ "stats_except.h", "stats__except_8h.html", null ],
    [ "vecarray.tmp.h", "vecarray_8tmp_8h.html", "vecarray_8tmp_8h" ],
    [ "warnflags.h", "warnflags_8h.html", null ],
    [ "writetable.cpp", "writetable_8cpp.html", "writetable_8cpp" ]
];