# Common recipes for compiling project subdirectories
# by Krzysztof Findeisen
# Created April 28, 2013
# Last modified July 24, 2013

OBJS     := $(SOURCES:.cpp=.o)

#---------------------------------------
# Primary build option
PROJ := $(PROJ:=.a)
PROJ := $(PROJ:%=../lib%)
$(PROJ): $(OBJS)
	@echo "Packaging $@..."
	@$(AR) $(ARFLAGS) $@ $^
